fix(react/twig) - refactor headings to improve accessiblity
international-labour-organization/designsystem pull request #900
Opened 2024-03-28 07:18 UTC by Shashika6

Fixes https://github.com/international-labour-organization/designsystem/issues/865

### Notes :- 

* Currently h3 tags are used in cards which causes issues in accessibility in order of headings

### Solution :- 

* Refactor `h3` tags to be` p` tags by default.
* Add new prop called titleElement if a heading element needs to be added

2024-04-02 14:17 UTC, justintemps commented
Hey @bashlk in the React package, you need to fix the options provided for Storybook. It should be like a dropdown with a list of the supported elements. Right now it's set to be a generic object which is not right.

<img width="1002" alt="image" src="https://github.com/international-labour-organization/designsystem/assets/12401179/9ff4394f-ac45-4a84-88d9-3c52f80c4cc8">

2024-04-02 14:21 UTC, justintemps commented
@Shashika6 the above comment goes for the Detail Card. The Factlist and Multilink Card don't seem to have the option in Storybook, which is a mistake.

2024-04-02 16:34 UTC, Shashika6 commented
Hey @justintemps added a dropdown to select titleElement options in both twig and react.


<img width="1471" alt="Screenshot 2024-04-02 at 21 49 56" src="https://github.com/international-labour-organization/designsystem/assets/32934169/58f8e84d-1847-4b17-80c3-0242de1c40b2">

2024-04-03 07:27 UTC, justintemps requested changes
Hey @Shashika6 this looks mostly good, we just need to make sure that "p" is included among the options provided to the user.

2024-04-03 07:27 UTC, justintemps commented on .changeset/small-brooms-destroy.md
> +Address accessibility issues with heading order in cards by changing `<h3>` tags to `<p>`, Additionaly add an optional prop that allows for configuration of the title element if needed.
I would change this to:

Address accessibility issues with the heading order of cards by changing the default element used to render the title from an `<h3>` to `<p>`. Additionaly add an optional prop that allows for configuration of the title element if needed.

2024-04-03 07:27 UTC, justintemps commented on packages/react/src/types/index.ts
> +export type HeadingTypes = "h1" | "h2" | "h3" | "h4" | "h5" | "h6";
@Shashika6 This should include `"p"` if that's the default for cards.

2024-04-03 07:27 UTC, justintemps commented on packages/react/src/stories/Card/DetailCard.stories.tsx
> +      options: ["h1", "h2", "h3", "h4", "h5"],
@Shashika6 for all cards, this should include "p" or else the user won't be able to return to the default.

2024-04-03 07:27 UTC, justintemps commented on packages/twig/src/patterns/components/card_detail/card_detail.wingsuit.yml
> +        h1: h1
@Shashika6 here again, the options need to include the default which is "p"

2024-04-03 14:34 UTC, Shashika6 commented
Made the changes you requested @justintemps :)

2024-04-05 08:29 UTC, justintemps commented
Hey @Shashika6, I added some more things here:

- Changed `titleElement` to `titleLevel` which I think is clearer
- Allowed the `titleLevel` to be set from the Card Group for all cards in the group

Which I was doing the later, I noticed that the Card Group in React still needs to be synced with the Card Group in Twig. There are some settings that are missing (alignment etc.). Could you open a ticket and take care of that?

2024-04-05 08:33 UTC, Shashika6 commented
Will do @justintemps 🫡

2024-04-05 08:38 UTC, merged